### ISSUE TITLE
Develop contact us page

### ISSUE THREAD

**Issue by roymoran** [NuevoFoundation/nuevofoundation-web#134]
Contact Us page currently does not have much content, recommended to migrate message submission form from current website in the mean time.

**Comment by edengarza** [comment]
Created PR #138 for this task.

**Comment by cprivera** [comment]
closed #138 with initial re-working of Contact Us page. next up is changing style of submission form and adding functionality to submit message and display nuvi image and allow for user to dismiss image.

**Comment by edengarza** [comment]
Created PR #146 for updating the styles.

**Comment by jeremiahjordanisaacson** [comment]
Closing this issue.
