### ISSUE TITLE
Page: What We Do

### ISSUE THREAD

**Issue by Sunny-Dee** [NuevoFoundation/nuevofoundation-web#159]
- Fix 3 header images so they are centered properly on PC browser.
- Add anchor links from top images/text to corresponding section.
- Add alt text on ALL images (e.g. "Coding workshops" "Image of Students in Nuevo Foundation coding workshop" Image of Students in Nuevo Foundation virtual session" "Image of Students at Nuevo Foundation speaker series"
- Roy to speak with Izzy about image placement/scaling.

**Comment by jeremiahjordanisaacson** [comment]
Closing this issue.
