### ISSUE TITLE
Email Donorbox about form validation missing on "In Honor of.."

### ISSUE THREAD

**Issue by roymoran** [NuevoFoundation/nuevofoundation-web#165]

**Comment by Sunny-Dee** [comment]
Can we get a little more explanation on this? As in:
- Do we want to validate for no curse words?
- Validate for <First Name> <Last Name> format?
- Should it be an email?

**Comment by roymoran** [comment]
When selecting the "Dedicate my donation in honor or in memory of someone" - there is an input for "Recipient Email". Jeremiah noticed that Donorbox does not validate this email when you continue to the next step of the form. The idea for this issue was to follow up with Donorbox since this may be a gap in their product that they can resolve. If they won't be resolving it, we can validate the field on the client side. 

<img width="488" alt="Screen Shot 2019-09-26 at 7 34 47 PM" src="https://user-images.githubusercontent.com/4195689/65733524-c831cf80-e094-11e9-8122-bdd19997bc45.png">

**Comment by jeremiahjordanisaacson** [comment]
Closing as Donorbox has resolved this issue.
