### ISSUE TITLE
Page: Home

### ISSUE THREAD

**Issue by Sunny-Dee** [NuevoFoundation/nuevofoundation-web#181]
- Down arrow show be anchor link to below content.
- Add descriptive alt tags over number context by "The challenge kids face" section.
- Consider "Three-fold" area to have dark "1" "2" "3" icons next to text. Izzy could provide a suggestion here.
- JavaScript to scroll numbers up on "The impact we had:" section.
- Consider adding "stars" and a "Nuvi" constellation to the bottom image of the Earth, sync with Izzy.
- Roy to talk to Izzy

**Comment by jeremiahjordanisaacson** [comment]
Closing issues.
