### ISSUE TITLE
Update "The impact we had:" numbers to count up from zero.

### ISSUE THREAD

**Issue by jeremiahjordanisaacson** [NuevoFoundation/nuevofoundation-web#212]
Please update "This impact we had:" numbers to animate counting up from zero.

**5,358**
Diverse
students

**80%**
More interested
in STEM

**91%**
Believed they
learned to code

**Example demo:** https://www.jqueryscript.net/demo/Counting-Up-To-Numerical-Values-On-Scroll-jQuery-Countup-js/
**Sample Code:** https://www.jqueryscript.net/other/Counting-Up-To-Numerical-Values-On-Scroll-jQuery-Countup-js.html
**Note:** Use whatever technology you prefer to accomplish this, jQuery would work but if you have a better solution please pursue it. Thanks!

**Comment by jeremiahjordanisaacson** [comment]
Checking in. Any updates on progress? If not, that's cool! Just wondering. :) Thanks!

**Comment by xcortez0009** [comment]
I don’t have any updates

Sent from my iPhone

On Jun 29, 2020, at 7:04 PM, Jeremiah Isaacson <notifications@github.com> wrote:

﻿

Checking in. Any updates on progress? If not, that's cool! Just wondering. :) Thanks!

**Comment by adileneconstante** [comment]
Hi all! Sorry I missed today. I’m just clocking off work. Update for the
css animations: have a rough first pass working, it’s not final yet but
hoping to wrap things up by next meeting.

Best,
Adilene

**Comment by jeremiahjordanisaacson** [comment]
Closing this one since we got it!
