### ISSUE TITLE
README for the Nuevo Foundation's GitHub Homepage

### ISSUE THREAD

**Issue by Verisimilitude11** [NuevoFoundation/nuevofoundation-web#274]
Are there any plans to initialize a .github repository and add a README.md to it? This is similar to a README for individual repositories, but it will appear on the GitHub organization page. If so, I'm ready to create one. This will improve the homepage and provide instructions for navigating the repositories/directing them to documents necessary for contributing. For example:
<img width="722" alt="Screenshot 2022-08-03 141548" src="https://user-images.githubusercontent.com/96280466/182713433-5a40bc30-050c-4f9b-8f96-67e0e41ee443.png">
Thoughts/questions?

**Comment by jeremiahjordanisaacson** [comment]
@Verisimilitude11 Go ahead and create one. I can work on the actual content but you kick off the main page.

**Comment by jeremiahjordanisaacson** [comment]
@Verisimilitude11 Actually I got this one. Thank you for the suggestion! This is awesome! I will add the content but you get all the credit and extra points for discovering this feature!

**Comment by Verisimilitude11** [comment]
Sounds good, thank you!

**Comment by jeremiahjordanisaacson** [comment]
Check this out:

[](https://github.com/NuevoFoundation)

<img width="794" alt="image" src="https://user-images.githubusercontent.com/777517/183232993-b1f07445-a786-4c1a-8713-2cf9a0096fc3.png">

**Comment by Verisimilitude11** [comment]
It looks great! Awesome work!

**Comment by Verisimilitude11** [comment]
We can also include a small section tomorrow with a quick call to action for how people can get involved.
