### ISSUE TITLE
Design Support us page

### ISSUE THREAD

**Issue by roymoran** [NuevoFoundation/nuevofoundation-web#75]

**Comment by Crea-Ive** [comment]
Done! here's the link for comps, redlines and assets: https://teams.microsoft.com/_#/files/Design?threadId=19%3A764b1a304d774a2892df966c4026b3e5%40thread.skype&ctx=channel&context=05_WorkingFiles%252F04_Support_page

**Comment by Crea-Ive** [comment]
@roymoran  feel free to take a look at the updated comps!
