### ISSUE TITLE
Update text on site

### ISSUE THREAD

**Issue by beagandica** [NuevoFoundation/nuevofoundation-web#87]

**Comment by beagandica** [comment]
Please update the text on Nuevo Site under FAQ to the below!? Thank you!!!

What is a virtual session?
A virtual session is an opportunity for your students to talk to someone at Microsoft or any other tech company over Teams/Skype/Hangouts/Zoom who is excited and passionate about technology and sharing their experience at their workplace. You can use this as a way for your students to learn about what it's like to work in technology. We also use the time to have the students ask questions about tech or anything they're curious about.

**Comment by Sunny-Dee** [comment]
This was updated after the hackathon.
